# # # # # # # # # #
#   D i A n A :)  #
# # # # # # # # # #

# Basic
name:               "diana lam"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           redcarpet
highlighter:        rouge

# Analytics
google_analytics:   UA-72320233-1

# Navigation
nav:
  - name:           "about"
    href:           "/about"
  - name:           "github"
    href:           "https://github.com/dianalam"
  - name:           "linkedin"
    href:           "https://www.linkedin.com/in/diana-lam-45a48726"
  - name:           "design"
    href:           "https://dianalam.carbonmade.com"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
